name: Preview

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on: 
  push:
    branches-ignore: [main]

jobs:
  dependencies: 
    name: Install and Cache Dependecies
    runs-on: ubuntu-22.04
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get pnpm Store Directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Dependencies
        run: pnpm install
      - name: Upload Dependecies
        uses: actions/upload-artifact@v3
        with: 
          name: dependencies
          path: node_modules

  build:
    name: Build
    needs: dependencies
    runs-on: ubuntu-22.04
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - name: Download Dependecies
        uses: actions/download-artifact@v3
        with: 
          name: dependencies
          path: node_modules
      - name: Run Build
        run: pnpm build
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with: 
          name: build
          path: .next
      
  
  test:
    name: Test
    needs: [dependencies, build]
    runs-on: ubuntu-22.04
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - name: Download Dependecies
        uses: actions/download-artifact@v3
        with: 
          name: dependencies
          path: node_modules
      - name: Download Build
        uses: actions/download-artifact@v3
        with: 
          name: build
          path: .next
      - name: Run Test
        run: pnpm test